Browser page
ionic-team/capacitor-testapp pull request #9
Opened 2020-08-28 19:24 UTC by ikeith

2020-09-09 16:08 UTC, jcesarmobile requested changes
added to minor suggestions

since prefetch is Android only, maybe you can use it only for Android? or put it in a try catch since iOS rejects

also, since browser don't have events, the automatic close is not working, I think you can move the close code outside the event listener, maybe with a bigger timeout

2020-09-28 12:44 UTC, jcesarmobile commented on src/pages/Browser.tsx
> +    Browser.prefetch({ urls: ['https://capacitorjs.com'] });
```suggestion
```

prefetch was removed, remove usage

2020-09-28 12:44 UTC, jcesarmobile commented on src/pages/Browser.tsx
> +    finishedHandler = Browser.addListener('browserFinished', async info => {
```suggestion
    finishedHandler = Browser.addListener('browserFinished', async () => {
```
doesn't return info anymore

2020-09-28 12:45 UTC, jcesarmobile commented on src/pages/Browser.tsx
> +    loadedHandler = Browser.addListener('browserPageLoaded', async info => {
```suggestion
    loadedHandler = Browser.addListener('browserPageLoaded', async () => {
```
doesn't return info anymore

2020-09-28 15:09 UTC, jcesarmobile commented
Since the web platform don't have the `browserPageLoaded` event it's not possible to test the close method there

2020-10-14 20:03 UTC, dwieeb approved these changes

2020-10-14 22:30 UTC, merged